.\"
.\" Generated automatically from mk_man -- the manpage "templater" 
.\"
.\" Man page for tns_util
.\"
.\" Copyright (c) 2000, Thomas Pantzer <pantec@informatik.uni-leipzig.de>.
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the README file that comes with the tns_util
.\" distribution.  
.\"
.\" University of Leipzig
.\"
.\" Many changes - aeb
.\"
.\" learning the man-style ?? 
.\" type at the prompt>> man 7 man [ENTER]
.\"
.TH tns_util 3 "February 08, 2000"
.LO 1
.SH NAME
.\" Abstract section
.\"
tns_util \- make short
.SH SYNOPSIS
tns_util  [\fB-i\fR] [\fB-o\fR \fIdemo option arg\fR]
.\"
.SH DESCRIPTION
.B tns_util
does the following by ... 
.BR
blabla
.PP
or many more foobar 
.\"
.SH OPTIONS

.TP
.B \-\^i
.\" text for option 1
make trouble

.TP
.B \fB\-\^o\fR \fIdemo option arg\fR
.\" text for option 2
make trouble if \fIdemo option arg\fR is not empty

.\"
.SH ENVIRONMENT
No environment variables are used
.\"
.SH "SEE ALSO"
many other programs
.\"
.SH BUGS
no bugs discovered
.\"
.SH AUTHOR
pantecs mailtest, pantec@zorro, 2000
.\"
.\"
